# Config for Self-Forcing training with autoregressive rollout
model:
  model_id: causal_game_rft
  sample_size: [5,8]
  channels: 128
  
  n_layers: 17
  n_heads: 16
  d_model: 1024

  tokens_per_frame: 16
  n_buttons: 11
  n_mouse_axes: 2

  cfg_prob: 0.0
  n_frames: 48

  causal: true

train:
  trainer_id: self_forcing
  data_id: cod_latent
  data_kwargs:
    window_length: 48
    root: ../cod_data/BlackOpsColdWar
    add_optical_flow: false

  target_batch_size: 256
  batch_size: 32

  epochs: 200

  opt: AdamW
  opt_kwargs:
    lr: 2.0e-6
    weight_decay: 1.0e-4
    eps: 1.0e-15
    betas: [0.9, 0.95]

  scheduler: null

  checkpoint_dir: checkpoints/self_forcing-360p

  student_ckpt: null
  teacher_ckpt: null

  sample_interval: 1000
  save_interval: 5000

  n_samples: 8

  vae_id: 720pr3dc
  vae_batch_size: 4
  vae_scale: 0.35
  vae_cfg_path: configs/owl_vaes/128x_cod_stage2.yml
  vae_ckpt_path: 720p_cod_vae_30m_35k_steps.pt

  teacher_ckpt: null # Set later TODO

wandb:
  name: samibg
  project: video_models
  run_name: self_forcing_360p