model_checkpoint_path: "/home/sami/owl-wms/checkpoints/wm/dcae_hf_cod/ckpt_165k_ema.pt"
run_config_path: "/home/sami/owl-wms/checkpoints/wm/dcae_hf_cod/basic.yml"
device: "cuda"

stream_config:
  fps: 20
  frames_per_batch: 60
  window_length: 60
  device: "cuda"
  n_buttons: 11
  n_mouse_axes: 2
  mouse_range: [-1.0, 1.0]
  action_margin_px_height: 150

sampling_config:
  sampling_steps: 20
  vae_scale: 1.0
  cfg_scale: 1.3
  window_length: 60
  num_frames: 60
  noise_prev: 0.2

run_config: null # loaded at runtime from model_config_path, and used to access model and train config


